name: Deploy Landing

on:
  push:
    branches:
      - "main"

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install NPM dependencies
        run: npm install

      - name: Deploy landing page
        run: npm run deploy
